#!/usr/bin/env bun

import { createHash } from "node:crypto"
import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs"
import { dirname, join, relative } from "node:path"

interface AssetEntry {
  readonly path: string
  readonly mode: number
  readonly sha256: string
  readonly dataBase64: string
}

const packageJson = JSON.parse(readFileSync("package.json", "utf8")) as {
  readonly name?: string
  readonly version?: string
}

const outputPath = join("src", "generated", "runtimeAssets.ts")
const assetRoots = ["ios", join("src", "bridge", "lldb-python", "bridge.py")]

const shouldIncludePath = (path: string): boolean => {
  const parts = path.split("/")
  const name = parts.at(-1) ?? ""

  if (name === ".DS_Store" || name.endsWith(".xcuserstate")) {
    return false
  }

  if (parts.includes("xcuserdata") || parts.includes(".build")) {
    return false
  }

  return true
}

const collectFiles = (path: string): readonly string[] => {
  if (!shouldIncludePath(path)) {
    return []
  }

  const stats = statSync(path)

  if (stats.isFile()) {
    return [path]
  }

  if (!stats.isDirectory()) {
    return []
  }

  return readdirSync(path)
    .flatMap((entry) => collectFiles(join(path, entry)))
    .sort()
}

const assets: readonly AssetEntry[] = assetRoots
  .flatMap((root) => collectFiles(root))
  .map((path) => {
    const content = readFileSync(path)
    return {
      path: relative(".", path),
      mode: statSync(path).mode & 0o777,
      sha256: createHash("sha256").update(content).digest("hex"),
      dataBase64: content.toString("base64"),
    }
  })
  .sort((left, right) => left.path.localeCompare(right.path))

const hash = createHash("sha256")
for (const asset of assets) {
  hash.update(asset.path)
  hash.update("\0")
  hash.update(String(asset.mode))
  hash.update("\0")
  hash.update(asset.sha256)
  hash.update("\0")
}

const manifest = {
  packageName: packageJson.name ?? "@skastr0/probe",
  packageVersion: packageJson.version ?? "0.0.0",
  assetHash: hash.digest("hex"),
  assets,
}

const source = `// Generated by scripts/generate-runtime-assets.ts. Do not edit by hand.

export interface ProbeRuntimeAsset {
  readonly path: string
  readonly mode: number
  readonly sha256: string
  readonly dataBase64: string
}

export interface ProbeRuntimeAssetManifest {
  readonly packageName: string
  readonly packageVersion: string
  readonly assetHash: string
  readonly assets: readonly ProbeRuntimeAsset[]
}

export const probeRuntimeAssetManifest = ${JSON.stringify(manifest, null, 2)} as const satisfies ProbeRuntimeAssetManifest
`

mkdirSync(dirname(outputPath), { recursive: true })
writeFileSync(outputPath, source)

console.log(`Generated ${outputPath} with ${assets.length} runtime assets (${manifest.assetHash.slice(0, 12)})`)
